name: Spellcheck Action Check
on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - '**/*.md'
      - '**/*.mdx'
    
  push:
    branches: [ main, dev ]
    paths:
      - '**/*.md'
      - '**/*.mdx'



jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.51.0
      name: Spellcheck
      with:
        config_path: spellcheck.yaml
        output_file: spellcheck-results.txt
    - name: Format spellcheck results
      if: failure()
      run: node scripts/format-spellcheck.js
